@startuml
'https://plantuml.com/sequence-diagram

autonumber

Пользователь -> Сервис_календаря: Организуй встречу на 2 часа на след неделе

Сервис_календаря --> Компонент_доступных_слотов_времени: Найди доступные слоты времени (с учетом недельнго расписания)

Компонент_доступных_слотов_времени --> Компонент_доступных_слотов_времени: Поиск свободных слотов, за вычетом встреч
Компонент_доступных_слотов_времени -> Сервис_календаря: Доступны 3 слота
Сервис_календаря -> Компонент_организации_встреч: Создай голосование для участников с вариантами
Компонент_организации_встреч -> Компонент_организации_встреч: Создание голосования
Компонент_организации_встреч -> Сервис_уведомлений: Создание оповещений о голосовании
Компонент_организации_встреч -> Сервис_календаря: Созданы голосования
Сервис_календаря --> Сервис_календаря: Голосование просрочено? Если да то отмени встречу.
Сервис_календаря --> Сервис_уведомлений: Оповести участников, что встреча отменена.
Сервис_уведомлений --> Участник: Встреча отменена

Участник --> Сервис_календаря: Голосую за слот времени
Сервис_календаря -> Сервис_календаря: Сохрани голос, \n отметь встречу как согласованную если все отметились.  \n Создай событие в календаре.
Сервис_календаря --> Сервис_уведомлений: Оповести участников, что встреча согласована.
Сервис_уведомлений --> Участник: Встреча согласована

@enduml